### ISSUE TITLE
when I run the mpirun_main.py, I have this error

### ISSUE THREAD

**Issue by talent2018** [namidairo777/Distributed-MADDPG#3]
mpirun_main.py at 292 code : total_action_dim = total_action_dim + env.action_space[i].n
AttributeError: 'Box' object has no attribute 'n'
can you help me,please! thanks

**Comment by namidairo777** [comment]
@talent2018 
Hi~
please check what kind of methods are there in this Box object,
Maybe reference changed due to `env` version upgrade

**Comment by namidairo777** [comment]
Since this seems to be dependency issue. I will close it
